# Generated by Django 5.1.2 on 2024-11-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_videoapiresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoapiresponse",
            name="session_key",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
